### ISSUE TITLE
'=' rendering

### ISSUE THREAD

**Issue by TieWay59** [roife/notes#3]
https://github.com/roife/notes/blob/ccf8b388581f96eac71c5e0b5ccb3213fd99328e/posts/cpp-primer-7-classes.org#L179

![图片](https://user-images.githubusercontent.com/40034603/91791380-9383ac00-ec45-11ea-9327-d94592e2bb16.png)

This could be some tag, but didn't be rendered correct in Github.
This make the text more confusing somehow. plz check is this what you want.

**Comment by roife** [comment]
The problem was caused by the rendering engine for Org files of GitHub, and I have just converted all Org files to Markdown with `Pandoc`.

While `Pandoc` cannot deal with Org files perfectly, some bugs were produced during conversion, and I will fix them later today.

**Comment by roife** [comment]
I have already fixed most of the problems (including what you mentioned), but when `|` appears in tables, the markdown parser of GitHub cannot parse it correctly yet.

So it is better to clone the repo and read with VSCode (it can render perfectly) or other readers when you have trouble with rendering problems.

**Comment by TieWay59** [comment]
I got it, so I suggested checking the syntax is reasonable as you expect.
Static blog is fun, I used to keep one hexo blog when i have quadruple spare-time.
